version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
    - "albertospelta"
    ignore:
      - dependency-name: "Microsoft.NET.Test.Sdk"
      - dependency-name: "xunit"
      - dependency-name: "xunit.runner.visualstudio"
      - dependency-name: "coverlet.collector"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
    - "albertospelta"