name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    name: build-and-test--${{ matrix.os-version }}
    runs-on: ${{ matrix.os-version }}
    strategy:
      matrix:
        os-version: [windows-latest] #, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
          global-json-file: global.json
      - name: restore
        run: dotnet restore ./src
      - name: build
        run: dotnet build ./src/Dax.Formatter.sln --configuration Release --no-restore
      - name: test
        run: dotnet test ./src/Dax.Formatter.Tests/Dax.Formatter.Tests.csproj --configuration Release --no-build --verbosity normal
      - name: pack
        run: dotnet pack ./src/Dax.Formatter/Dax.Formatter.csproj --configuration Release --no-build --no-restore --verbosity normal